server:
  port: 8086

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb+srv://admin:1password123@cluster0.aodaufp.mongodb.net/
      database: chat_notification

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/