replicaCount: 2

image:
  repository: docker.io/chat-app/realtime-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4000
  containerPort: 4000

env:
  - name: NODE_ENV
    value: production
  - name: KAFKA_BROKER
    value: kafka:9092
  - name: REDIS_HOST
    value: redis
  - name: MONGO_URI
    value: mongodb://mongo:27017/chat_app
  - name: JWT_PUBLIC_KEY
    value: |-
      -----BEGIN PUBLIC KEY-----
      <your-public-key>
      -----END PUBLIC KEY-----

ingress:
  enabled: true
  host: realtime.chat-app.local

livenessProbe:
  enabled: true
  path: /health
  port: 4000
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: /health
  port: 4000
  initialDelaySeconds: 5
  periodSeconds: 5
