replicaCount: 2

image:
  repository: docker.io/chat-app/file-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8084
  containerPort: 8080

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
  - name: MONGO_URI
    value: mongodb://mongo:27017/chat_app
  - name: MINIO_ENDPOINT
    value: minio:9000
  - name: MINIO_ACCESS_KEY
    value: minioadmin
  - name: MINIO_SECRET_KEY
    value: minioadmin

ingress:
  enabled: true
  host: file.chat-app.local
