replicaCount: 2

image:
  repository: docker.io/chat-app/auth-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  containerPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
  - name: MONGO_URI
    value: mongodb://mongo:27017/chat_app
  - name: JWT_PUBLIC_KEY
    value: |-
      -----BEGIN PUBLIC KEY-----
      <your-public-key>
      -----END PUBLIC KEY-----

ingress:
  enabled: true
  host: auth.chat-app.local

livenessProbe:
  enabled: true
  path: /actuator/health
  port: 8080
  initialDelaySeconds: 30
  periodSeconds: 15

readinessProbe:
  enabled: true
  path: /actuator/health
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5
