server:
  port: 8084

spring:
  application:
    name: group-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: group-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  data:
    mongodb:
      uri: mongodb+srv://admin:1password123@cluster0.aodaufp.mongodb.net/
      database: chat_group

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false
  packages-to-scan: com.chatapp.groupservice
  paths-to-match: /api/**

