replicaCount: 2

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  containerPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

env: []
ingress:
  enabled: false
  host: example.local

livenessProbe:
  enabled: false
  path: /actuator/health
  port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: false
  path: /actuator/health
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5
